name: Update Lambda Layers
# This workflow runs early Tuesday morning.
# It runs the copy-layer.sh bash script for prod and nonprod

on:
  schedule:
    - cron:  '11 2 * * 2'
  workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DT_PROD_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2
          role-duration-seconds: 1800
      - name: Run Copy Layer
        run: |
          ./copy-layer
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_REGION: eu-west-2